name: Cross-platform Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        os: [linux]
        arch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.5'
          cache: true
          cache-dependency-path: src/go.sum

      - name: Build binary for ${{ matrix.os }}-${{ matrix.arch }}
        working-directory: src
        run: |
          mkdir -p ../build
          env CGO_ENABLED=1 GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o ../build/myapp-${{ matrix.os }}-${{ matrix.arch }} .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: build/
